### ISSUE TITLE
AsTraitPath doesn't work when method returns `Self`

### ISSUE THREAD

**Issue by asterite** [noir-lang/noir#9162]
### Aim

This code:

```noir
trait Trait {
    fn method() -> Self;
}

impl Trait for Field {
    fn method() -> Self {
        0
    }
}

fn main() {
    let _ = <Field as Trait>::method();
}
```

Gives this compilation error:

```
error: Type annotation needed
   ┌─ src/main.nr:12:14
   │
12 │     let _ = <Field as Trait>::method();
   │              -------------- Could not determine type of generic argument
```

If the method returns a specific type, for example `Field`, the code compiles fine. It seems the error only happens when `Self` is returned.

Note that doing `let _ = Field::method();` works fine so there must be some difference between the two ways to do it.

This stopped working after #9146 was merged.

### Expected Behavior

The above code should compile fine.

### Bug

It doesn't compile.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
Duplicate of #9201
