### ISSUE TITLE
Error running `nargo` crate tests

### ISSUE THREAD

**Issue by ilitteri** [noir-lang/noir#401]
# Description

## Aim

Run the `nargo` crate tests.

## Expected behavior

After compiling, tests should be run.

## Bug

Tests doesn't run because of a compilation error

```shell
error: linking with `cc` failed: exit status: 1

...

  = note: ld: library not found for -lomp
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `nargo` due to previous error
```

# To reproduce

> Note: Not all users could reproduce this.

1. Clone the repo.
2. `cd crates/nargo`.
3. `cargo t`

# Environment

- OS: macOS Monterey 12.6

# Additional context

The `omp` library is not always to be found when compiling with `cc` even after running `brew install libomp`.

**Comment by ilitteri** [comment]
A temporary hardcoded solution could be to create a `.cargo` directory inside the `nargo` crate with a `config` file containing the following

```toml
[build]
rustflags = ["-L<libomp path>"]
```

Where `<libomp path>` is the path for `libomp` which in my case is in `/usr/local/opt/llvm/lib/libomp/lib` after making `brew install libomp llvm`.

Despite the above, a non-hardcoded solution should be found before making a fix PR.

**Comment by oberstet** [comment]
hooray! so this

```
sudo apt install libomp-14-dev
cd crates/nargo
mkdir .cargo

(base) oberstet@intel-nuci7:~/scm/3rdparty/noir/crates/nargo$ cat .cargo/config.toml 
[build]
rustflags = ["-L/usr/lib/llvm-14/lib"]
```

worked on ubuntu 22.04:

```
   Compiling aztec_backend v0.1.0 (https://github.com/noir-lang/aztec_backend?rev=01b922adcb5a9d70b2d12304e1cb7487d9f28188#01b922ad)
   Compiling noirc_driver v0.1.0 (/home/oberstet/scm/3rdparty/noir/crates/noirc_driver)
    Finished release [optimized] target(s) in 1m 50s
  Installing /home/oberstet/.cargo/bin/nargo
   Installed package `nargo v0.1.0 (/home/oberstet/scm/3rdparty/noir/crates/nargo)` (executable `nargo`)
(base) oberstet@intel-nuci7:~/scm/3rdparty/noir/crates/nargo$ nargo -V
nargo 0.1
(base) oberstet@intel-nuci7:~/scm/3rdparty/noir/crates/nargo$ nargo --help
nargo 0.1
Kevaundray Wedderburn <kevtheappdev@gmail.com>
Noir's package manager

USAGE:
    nargo [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    build       Builds the constraint system
    compile     Compile the program and its secret execution trace into ACIR format
    contract    Creates the smart contract code for circuit
    gates       Counts the occurences of different gates in circuit
    help        Prints this message or the help of the given subcommand(s)
    new         Create a new binary project
    prove       Create proof for this program
    verify      Given a proof and a program, verify whether the proof is valid
(base) oberstet@intel-nuci7:~/scm/3rdparty/noir/crates/nargo$ 
```

**Comment by ilitteri** [comment]
Closing this because this test does not fail when running the workspace's tests in the CI.
